# Generated by Django 4.0.5 on 2022-06-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiveAway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='giveaways')),
            ],
        ),
    ]
